# .goreleaser.yaml
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: ask-binary
    binary: ask
    main: ./cmd/main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X Qwen-cli/version.Version={{.Version}}
      - -X Qwen-cli/version.GitCommit={{.Commit}}
      - -X Qwen-cli/version.BuildDate={{.Date}}
    # goversion: '1.24.1' # Specify Go version in build settings (deprecated in v2)

release:
  github:
    owner: oAo-lab
    name: Qwen-cli
  name_template: 'v{{ .Version }}'
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - '^test:'
      - '^ci:'
      - '^docs:'
      - '^chore:'
      - '^refactor:'
      - '^style:'
