# .goreleaser.yaml
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: ask-binary
    binary: ask
    main: ./cmd/main.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X Qwen-cli/version.Version={{.Version}}
      - -X Qwen-cli/version.GitCommit={{.Commit}}
      - -X Qwen-cli/version.BuildDate={{.Date}}
    # goversion: '1.24.1' # Specify Go version in build settings (deprecated in v2)

  - id: ask-updater
    binary: ask_updater
    main: ./cmd/updater/main.go
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X Qwen-cli/version.Version={{.Version}}
      - -X Qwen-cli/version.GitCommit={{.Commit}}
      - -X Qwen-cli/version.BuildDate={{.Date}}

archives:
  - id: ask-archives
    builds:
      - ask-binary
    format: tar.gz
    name_template: 'Qwen-cli_{{.Version}}_{{.Os}}_{{.Arch}}'
    files:
      - none*  # 只包含二进制文件，不包含其他文件

  - id: ask-windows-exe
    builds:
      - ask-binary
    format: binary  # Windows 直接发布 exe 文件
    name_template: 'ask_{{.Version}}_{{.Os}}_{{.Arch}}'
    allow_different_binary_count: true

  - id: ask-updater-exe
    builds:
      - ask-updater
    format: binary  # Windows 更新器直接发布 exe 文件
    name_template: 'ask_updater_{{.Version}}_{{.Os}}_{{.Arch}}'
    allow_different_binary_count: true

release:
  github:
    owner: oAo-lab
    name: Qwen-cli
  name_template: 'v{{ .Version }}'
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - '^test:'
      - '^ci:'
      - '^docs:'
      - '^chore:'
      - '^refactor:'
      - '^style:'
